### PR TITLE
[core] Bumped up to MC1.19.1

### LINKED ISSUE #71: 1.19.1 support?
I noticed the mod does not work on 1.19.1. How feasible is it for support to be added?

### PR DESCRIPTION
**Pull request by lonefelidae16**
resolve #71 

This changes works for me. I did not change the MOD version string.

Please check the changes below:

* `gradle.properties`
  - `minecraft_version` was set to 1.19.1
  - `fabric_api_version` was set to minimum requirement version 0.57.1

* method signature was changed, affecting `ChatSound.java`
  - net.minecraft.client.gui.hud.ChatHud#addMessage

### CODE REVIEW

**Comment by Disguys** [comment]
@lonefelidae16 add compalitable for 1.19.2 pls

**Comment by lonefelidae16** [comment]
> add compalitable for 1.19.2 pls

This patch also works on 1.19.2, try it.

**Comment by Disguys** [comment]
> > add compalitable for 1.19.2 pls
> 
> This patch also works on 1.19.2, try it.

Can you give me a download link?

**Comment by lonefelidae16** [comment]
> Can you give me a download link?

I’ve attached it to my repository: [lonefelidae16:update/MC1.19.1](https://github.com/lonefelidae16/extra-sounds/commit/cfca9a0161bbbd2ac7790b8dfd1a33268412679e#commitcomment-80678431)

**Comment by lonefelidae16** [comment]
duplicate #74

**Comment by akemin-dayo** [comment]
Ahhh… I'm sorry, I didn't see your existing PR before I publicised mine. I really didn't mean to overshadow you or anything!

**Pull request closed without merging**
